name: test-autorebuild
on: 
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  dl-new-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: connect to VPS
        uses: matheusvanzan/sshpass-action@v2
        with:
          host: ${{ secrets.IP_ADDRESS }}
          port: ${{ secrets.PORT }}
          user: ${{ secrets.USERNAME }}
          pass: ${{ secrets.PASSWORD }}
          run: | 
            cd /var/www/test-autobuild/ 
            git checkout main 
            git pull 
            systemctl reload apache2